# Generated by Django 5.0.7 on 2024-07-23 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_main', '0001_initial'),
        ('hackcraft', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('basegeneralfieldmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='custom_main.basegeneralfieldmodel')),
                ('key', models.CharField(max_length=17)),
                ('type', models.CharField(max_length=50)),
                ('is_child', models.BooleanField()),
                ('child', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='custom_main.widget')),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackcraft.hackathons')),
            ],
            bases=('custom_main.basegeneralfieldmodel',),
        ),
    ]
