# Generated by Django 5.0.7 on 2024-07-23 19:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('basegeneralfieldmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='custom_main.basegeneralfieldmodel')),
                ('user_type', models.CharField(blank=True, choices=[('student', 'student'), ('professional', 'professional')], default=' ', max_length=500, null=True)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(default=' ', max_length=250)),
                ('gender', models.CharField(default=' ', max_length=250)),
                ('city', models.CharField(default=' ', max_length=250)),
                ('organisation', models.CharField(default=' ', max_length=250)),
                ('cousrse_name', models.CharField(default=' ', max_length=250)),
                ('course_end_year', models.IntegerField(default=-1)),
                ('date_of_birth', models.DateField(null=True)),
                ('interest', models.JSONField(default={})),
                ('about', models.CharField(default=' ', max_length=3000)),
                ('education_qualification', models.CharField(default=' ', max_length=100)),
                ('specialization', models.CharField(default=' ', max_length=200)),
                ('percentage', models.IntegerField(default=-1)),
                ('degree', models.CharField(default=' ', max_length=200)),
                ('facebook', models.CharField(default=' ', max_length=100)),
                ('x', models.CharField(default=' ', max_length=50)),
                ('instagram', models.CharField(default=' ', max_length=100)),
                ('linkedin', models.CharField(default=' ', max_length=100)),
                ('github', models.CharField(default=' ', max_length=100)),
                ('medium', models.CharField(default=' ', max_length=100)),
                ('reddit', models.CharField(default=' ', max_length=100)),
                ('slack', models.CharField(default=' ', max_length=100)),
                ('dribble', models.CharField(default=' ', max_length=100)),
                ('behance', models.CharField(default=' ', max_length=100)),
                ('codepen', models.CharField(default=' ', max_length=100)),
                ('figma', models.CharField(default=' ', max_length=100)),
                ('phone', models.CharField(default=' ', max_length=10, null=True)),
                ('skill', models.ManyToManyField(blank=True, default=None, to='hackcraft.skill')),
            ],
            bases=('custom_main.basegeneralfieldmodel',),
        ),
        migrations.CreateModel(
            name='Hackathons',
            fields=[
                ('basegeneralfieldmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='custom_main.basegeneralfieldmodel')),
                ('type', models.CharField(choices=[('Custom', 'Custom'), ('Default', 'Default')], max_length=50)),
                ('logo', models.CharField(blank=True, default='', max_length=2000)),
                ('name', models.CharField(max_length=250)),
                ('organisation_name', models.CharField(default=None, max_length=250)),
                ('brief', models.TextField(default=None)),
                ('deadline', models.DateField()),
                ('start_date_time', models.DateTimeField()),
                ('team_size_min', models.IntegerField()),
                ('team_size_max', models.IntegerField(blank=True, null=True)),
                ('fee', models.CharField(blank=True, default=None, max_length=100)),
                ('total_number_rounds', models.IntegerField(blank=True, null=True)),
                ('form_exist', models.BooleanField(default=False)),
                ('number_of_registeration', models.IntegerField(blank=True, default=None, null=True)),
                ('template', models.CharField(default=' ', max_length=10)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hackathon_user', to='hackcraft.userprofile')),
            ],
            bases=('custom_main.basegeneralfieldmodel',),
        ),
    ]
